apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-web
  namespace: nginx-web

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-web

  template:
    metadata:
      labels:
        app: nginx-web

    spec:
      containers:
      - name: nginx
        image: adamk8s/nginx-web:v3

        ports:
        - containerPort: 80
