apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-http
  namespace: nginx-web

spec:
  podSelector:
    matchLabels:
      app: nginx-web

  policyTypes:
    - Ingress

  ingress:
    # Autorise le trafic HTTP vers nginx uniquement
    # depuis les pods ayant le label access=nginx
    - from:
        - podSelector:
            matchLabels:
              access: nginx
      ports:
        - protocol: TCP
          port: 80

    # Autorise le port de readiness du sidecar Istio
    - ports:
        - protocol: TCP
          port: 15021

    # Autorise Prometheus dans istio-system
    # à scraper les métriques du sidecar Istio
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 15020
